env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  linebreak-style:
    - error
    - windows
  max-len:
    - error
    - code: 130
      comments: 150
