env:
  node: true
  es6: true
  jest/globals: true
extends:
  - eslint:recommended
  - google
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  linebreak-style:
    - error
    - windows
  max-len:
    - error
    - code: 130
      comments: 150
  import/no-commonjs:
    - error
  import/no-deprecated:
    - error
  import/extensions:
    - error
    - ignorePackages
  import/order:
    - error
  import/no-default-export:
    - warn